### ISSUE TITLE
Serializing fully signed multisig transaction with toObject changes hash

### ISSUE THREAD

**Issue by andrewoons** [bitpay/bitcore-lib#18] opened 2015-11-10 13:01 UTC
When I have a fully signed Transaction object (2-of-3 signatures provided) and then inflate it to a JSON object through `var json = JSON.stringify(tx.toObject())`, it seems the hash of the transaction changes.

When I then do:
`var tx2 = new bitcore.Transaction(JSON.parse(json));` , it gives this error:

`throw new errors.InvalidState(message);`
`Invalid state: Hash in object does not match transaction hash`

If I try to broadcast the transaction through Insight before inflating it to JSON, it works perfectly fine. But when I convert that exact transaction through JSON and then back I get the error above.

Serializing the fully-signed transaction like `tx.serialize()` and then creating a new transaction from that value also works as it should. So it just related to fully-signed transactions using toObject() it seems.

I'd be happy to create a pull request for this if it indeed is a bug.

Update:

It should be possible to sign with one key, transform to JSON, send it to another client, sign with the other key and then send it back as JSON to the original client to then serialize and broadcast.

**Comment by andrewoons** [comment] 2015-11-12 22:11
I've done some more testing and it seems like the signatures and thus the correct script disappear completely when you sign the transaction the second time and then export to JSON. I'm currently testing some more to see if I can create a PR myself but any help / guidance would be appreciated.

**Comment by braydonf** [comment] 2015-11-13 22:28
This won't change the JSON output, however you can use the equivalent and shorter `JSON.stringify(tx)`. Not sure why the hash would change, I would compare the transaction before and after and see what changed.

**Comment by andrewoons** [comment] 2015-11-16 12:42
I've compared them and only the input script and scriptString have changed (along with the hash) after signing the transaction twice. 

This is the transaction before signing: 

```json
{
    "hash": "5d3197b2d795a446d4198bd6300b8fe286b5898907a096a83d7676a8a36d98cb",
    "version": 1,
    "inputs": [
        {
            "prevTxId": "4d7be95b6c9282a5b57f6215833dcd28a7b1a224f0b68d1e4d40a81e84ab190a",
            "outputIndex": 1,
            "sequenceNumber": 4294967295,
            "script": "004c69522102002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a210332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d121035fffe1dc00504e16881532d15920ce9ecdbb83c8dfe76b3fbfe99466a8eaffa353ae",
            "scriptString": "OP_0 OP_PUSHDATA1 105 0x522102002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a210332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d121035fffe1dc00504e16881532d15920ce9ecdbb83c8dfe76b3fbfe99466a8eaffa353ae",
            "output": {
                "satoshis": 577880,
                "script": "a914ac893bf0d78b686990377546d2ad40dc51d6854a87"
            },
            "threshold": 2,
            "publicKeys": [
                "02002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a",
                "0332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d1",
                "035fffe1dc00504e16881532d15920ce9ecdbb83c8dfe76b3fbfe99466a8eaffa3"
            ],
            "signatures": [
                null,
                null,
                null
            ]
        }
    ],
    "outputs": [
        {
            "satoshis": 40000,
            "script": "76a914410f5a2b899e2858085189a1360e13de58f0b32b88ac"
        },
        {
            "satoshis": 532350,
            "script": "a914ac893bf0d78b686990377546d2ad40dc51d6854a87"
        }
    ],
    "nLockTime": 0,
    "changeScript": "OP_HASH160 20 0xac893bf0d78b686990377546d2ad40dc51d6854a OP_EQUAL",
    "changeIndex": 1,
    "fee": 5530
}
```

Then after I've signed it:

```json
{
    "hash": "95a874c33b6523ac2ab339959ac1168b270ad14b1907a2cd9bc0a6651e5d3441",
    "version": 1,
    "inputs": [
        {
            "prevTxId": "4d7be95b6c9282a5b57f6215833dcd28a7b1a224f0b68d1e4d40a81e84ab190a",
            "outputIndex": 1,
            "sequenceNumber": 4294967295,
            "script": "00483045022100a2b49d65dd2dd02737d8664560879cfe22ab7a1050218e619bc322ddeae5562702206e4014bf546ba36572dd862a8a57a9bfe1b42650f5e519fcf0d308080c0161f60148304502210085f42257b4fecda676ad2014c5e6a0520dd18e141ebc0d22ba01f6aa303ff42702202dcb15c6a0a5670832b5360578fbe33d27acbda42ea1bc071de9a3a0deeec110014c69522102002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a210332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d121035fffe1dc00504e16881532d15920ce9ecdbb83c8dfe76b3fbfe99466a8eaffa353ae",
            "scriptString": "OP_0 72 0x3045022100a2b49d65dd2dd02737d8664560879cfe22ab7a1050218e619bc322ddeae5562702206e4014bf546ba36572dd862a8a57a9bfe1b42650f5e519fcf0d308080c0161f601 72 0x304502210085f42257b4fecda676ad2014c5e6a0520dd18e141ebc0d22ba01f6aa303ff42702202dcb15c6a0a5670832b5360578fbe33d27acbda42ea1bc071de9a3a0deeec11001 OP_PUSHDATA1 105 0x522102002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a210332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d121035fffe1dc00504e16881532d15920ce9ecdbb83c8dfe76b3fbfe99466a8eaffa353ae",
            "output": {
                "satoshis": 577880,
                "script": "a914ac893bf0d78b686990377546d2ad40dc51d6854a87"
            },
            "threshold": 2,
            "publicKeys": [
                "02002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a",
                "0332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d1",
                "035fffe1dc00504e16881532d15920ce9ecdbb83c8dfe76b3fbfe99466a8eaffa3"
            ],
            "signatures": [
                {
                    "publicKey": "02002b4401aa4990344b17fec0168bd6e0ed91b9576cbef05fe67e1bca16cd059a",
                    "prevTxId": "4d7be95b6c9282a5b57f6215833dcd28a7b1a224f0b68d1e4d40a81e84ab190a",
                    "outputIndex": 1,
                    "inputIndex": 0,
                    "signature": "3045022100a2b49d65dd2dd02737d8664560879cfe22ab7a1050218e619bc322ddeae5562702206e4014bf546ba36572dd862a8a57a9bfe1b42650f5e519fcf0d308080c0161f6",
                    "sigtype": 1
                },
                {
                    "publicKey": "0332bd1ca643339b04215fdc29e7cb44f361339d60fe56a5715a9fb5668dde97d1",
                    "prevTxId": "4d7be95b6c9282a5b57f6215833dcd28a7b1a224f0b68d1e4d40a81e84ab190a",
                    "outputIndex": 1,
                    "inputIndex": 0,
                    "signature": "304502210085f42257b4fecda676ad2014c5e6a0520dd18e141ebc0d22ba01f6aa303ff42702202dcb15c6a0a5670832b5360578fbe33d27acbda42ea1bc071de9a3a0deeec110",
                    "sigtype": 1
                },
                null
            ]
        }
    ],
    "outputs": [
        {
            "satoshis": 40000,
            "script": "76a914410f5a2b899e2858085189a1360e13de58f0b32b88ac"
        },
        {
            "satoshis": 532350,
            "script": "a914ac893bf0d78b686990377546d2ad40dc51d6854a87"
        }
    ],
    "nLockTime": 0,
    "changeScript": "OP_HASH160 20 0xac893bf0d78b686990377546d2ad40dc51d6854a OP_EQUAL",
    "changeIndex": 1,
    "fee": 5530
}
```

This is my code to sign the transaction:

```javascript
_.each(privKeys, function(privKey) {
			
    transaction = transaction.sign(new bitcore.PrivateKey.fromWIF(privKey));	

});
```

**Comment by braydonf** [comment] 2015-11-16 19:16
Added a few tests to see if I could reproduce this: https://github.com/bitpay/bitcore-lib/pull/20 however the tests are passing.

**Comment by Levino** [comment] 2015-11-22 09:19
I dont get it. What is the issue here? Could you post a complete node.js example that reproduces the error?

Maybe the _.each function is not be used "sync style" as it is being executed in parallel?

**Comment by andrewoons** [comment] 2015-11-22 11:53
Hmm I've also ran some tests myself locally and everything seems to work fine. I forgot to mention that I'm using Parse.com as my backend and I'm sending the JSON back to a cloud function to them and then back to my own node server. It looks like something is lost in that process.

I will do some more tests without the _.each function to see if that causes the problem but I think it's because Parse does some random formatting to JSON strings whenever they are passed in Cloud functions. If that's the case I don't think I can do too much about it unfortunately. I'll let you know!

**Comment by Levino** [comment] 2015-11-26 15:44
Please see 270b822f07c9cd5deccd8ac48af7dc8883e22193

I added a test in ``` /test/transaction/weirdBug.js ``` Is this the same bug?

**Comment by Levino** [comment] 2015-11-26 15:50
Has something to do with the "change" function of "Transaction". See 962f1b2e187c83ecbf8ae76644e5b7f1bc40e997

**Comment by fanatid** [comment] 2015-11-26 17:21
@Levino :clap: 
[fromObject](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L346) set [_changeScript](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L381) and [fee](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L384), but function [fee](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L661) call [_updateChangeOutput](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L838) that call [_clearSignatures](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L904) and in result Error throwing in [_checkConsistency](https://github.com/bitpay/bitcore-lib/blob/ae3435a4493e1591b024ba72e00b658d62bb2759/lib/transaction/transaction.js#L400) because restored transaction has other hash...

**Comment by braydonf** [comment] 2015-12-01 18:21
Addressed in https://github.com/bitpay/bitcore-lib/pull/25 Thanks @Levino and @fanatid

**Closed by braydonf** 2015-12-01 18:21 UTC
